# Generated by Django 5.1 on 2024-08-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
